datapoints = [ \
{ 'obj_type':'analogValue','obj_inst':566, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/studio1/electrical/total/demand/instant'},\
{ 'obj_type':'analogValue','obj_inst':544, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/studio1/electrical/total/demand/peak'},\
{ 'obj_type':'analogValue','obj_inst':563, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/studio1/electrical/total/demand/5minavg'},\
{ 'obj_type':'analogValue','obj_inst':564, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/studio1/electrical/total/demand/10minavg'},\
{ 'obj_type':'analogValue','obj_inst':565, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/studio1/electrical/total/demand/15minavg'},\
{ 'obj_type':'analogValue','obj_inst':557, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/studio1/electrical/total/demand/daytot'},\
{ 'obj_type':'analogValue','obj_inst':509, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/studio1/electrical/total/demand/weektot'},\
{ 'obj_type':'analogValue','obj_inst':508, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/studio1/electrical/total/demand/weekavg'},\
{ 'obj_type':'analogValue','obj_inst':492, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/studio1/electrical/total/demand/monthtot'},\
{ 'obj_type':'analogValue','obj_inst':568, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/studio1/electrical/total/voltage/instant'},\
{ 'obj_type':'analogValue','obj_inst':567, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/studio1/electrical/total/current/instant'},\
{ 'obj_type':'analogInput','obj_inst':3, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/studio1/electrical/DMR/demand/instant'},\
{ 'obj_type':'analogValue','obj_inst':362, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/studio1/electrical/DMR/demand/peak'},\
{ 'obj_type':'analogInput','obj_inst':22, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/studio1/electrical/DMR/voltage/instant'},\
{ 'obj_type':'analogInput','obj_inst':17, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/studio1/electrical/DMR/current/instant'},\
{ 'obj_type':'analogInput','obj_inst':4, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/studio1/electrical/AH8/demand/instant'},\
{ 'obj_type':'analogValue','obj_inst':458, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/studio1/electrical/AH8/demand/peak'},\
{ 'obj_type':'analogInput','obj_inst':21, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/studio1/electrical/AH8/voltage/instant'},\
{ 'obj_type':'analogInput','obj_inst':15, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/studio1/electrical/AH8/current/instant'},\
{ 'obj_type':'analogInput','obj_inst':2, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/studio1/electrical/AA/demand/instant'},\
{ 'obj_type':'analogValue','obj_inst':266, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/studio1/electrical/AA/demand/peak'},\
{ 'obj_type':'analogInput','obj_inst':20, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/studio1/electrical/AA/voltage/instant'},\
{ 'obj_type':'analogInput','obj_inst':16, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/studio1/electrical/AA/current/instant'},\
{ 'obj_type':'analogInput','obj_inst':1, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/studio1/electrical/K/demand/instant'},\
{ 'obj_type':'analogValue','obj_inst':170, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/studio1/electrical/K/demand/peak'},\
{ 'obj_type':'analogInput','obj_inst':24, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/studio1/electrical/K/voltage/instant'},\
{ 'obj_type':'analogInput','obj_inst':19, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/studio1/electrical/K/current/instant'},\
{ 'obj_type':'analogInput','obj_inst':0, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/studio1/electrical/J/demand/instant'},\
{ 'obj_type':'analogValue','obj_inst':74, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/studio1/electrical/J/demand/peak'},\
{ 'obj_type':'analogInput','obj_inst':23, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/studio1/electrical/J/voltage/instant'},\
{ 'obj_type':'analogInput','obj_inst':18, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/studio1/electrical/J/current/instant'}\
]
