datapoints = [ \
{ 'obj_type':'analogValue','obj_inst':566, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/1451/electrical/total/demand/instant'},\
{ 'obj_type':'analogValue','obj_inst':544, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/1451/electrical/total/demand/peak'},\
{ 'obj_type':'analogValue','obj_inst':563, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/1451/electrical/total/demand/5minavg'},\
{ 'obj_type':'analogValue','obj_inst':564, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/1451/electrical/total/demand/10minavg'},\
{ 'obj_type':'analogValue','obj_inst':565, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/1451/electrical/total/demand/15minavg'},\
{ 'obj_type':'analogValue','obj_inst':557, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/1451/electrical/total/demand/daytot'},\
{ 'obj_type':'analogValue','obj_inst':509, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/1451/electrical/total/demand/weektot'},\
{ 'obj_type':'analogValue','obj_inst':508, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/1451/electrical/total/demand/weekavg'},\
{ 'obj_type':'analogValue','obj_inst':492, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/1451/electrical/total/demand/monthtot'},\
{ 'obj_type':'analogValue','obj_inst':568, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/1451/electrical/total/voltage'},\
{ 'obj_type':'analogValue','obj_inst':567, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/1451/electrical/total/current/'},\
{ 'obj_type':'analogInput','obj_inst':3, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/1451/electrical/panel/DMR/demand/instant'},\
{ 'obj_type':'analogValue','obj_inst':362, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/1451/electrical/panel/DMR/demand/peak'},\
{ 'obj_type':'analogInput','obj_inst':22, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/1451/electrical/panel/DMR/voltage'},\
{ 'obj_type':'analogInput','obj_inst':17, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/1451/electrical/panel/DMR/current'},\
{ 'obj_type':'analogInput','obj_inst':4, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/1451/electrical/panel/AH8/demand/instant'},\
{ 'obj_type':'analogValue','obj_inst':458, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/1451/electrical/panel/AH8/demand/peak'},\
{ 'obj_type':'analogInput','obj_inst':21, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/1451/electrical/panel/AH8/voltage'},\
{ 'obj_type':'analogInput','obj_inst':15, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/1451/electrical/panel/AH8/current'},\
{ 'obj_type':'analogInput','obj_inst':2, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/1451/electrical/panel/AA/demand/instant'},\
{ 'obj_type':'analogValue','obj_inst':266, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/1451/electrical/panel/AA/demand/peak'},\
{ 'obj_type':'analogInput','obj_inst':20, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/1451/electrical/panel/AA/voltage'},\
{ 'obj_type':'analogInput','obj_inst':16, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/1451/electrical/panel/AA/current'},\
{ 'obj_type':'analogInput','obj_inst':1, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/1451/electrical/panel/K/demand/instant'},\
{ 'obj_type':'analogValue','obj_inst':170, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/1451/electrical/panel/K/demand/peak'},\
{ 'obj_type':'analogInput','obj_inst':24, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/1451/electrical/panel/K/voltage'},\
{ 'obj_type':'analogInput','obj_inst':19, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/1451/electrical/panel/K/current'},\
{ 'obj_type':'analogInput','obj_inst':0, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/1451/electrical/panel/J/demand/instant'},\
{ 'obj_type':'analogValue','obj_inst':74, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/1451/electrical/panel/J/demand/peak'},\
{ 'obj_type':'analogInput','obj_inst':23, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/1451/electrical/panel/J/voltage'},\
{ 'obj_type':'analogInput','obj_inst':18, 'prop_id':'presentValue', 'prefix':'/ndn/ucla.edu/bms/melnitz/data/1451/electrical/panel/J/current'}\
]
